
stages:
  - build
  - publish
  
variables:
  DATADOG_AGENT_WINBUILDIMAGES: v5996510-a9e6a7d
    
build:
  stage: build
  tags: ["runner:windows-docker", "windowsversion:1809"]
  script:
    - if (Test-Path build-out) { remove-item -recurse -force build-out }
    - if (Test-Path artifacts) { remove-item -recurse -force artifacts }
    - mkdir artifacts
    - echo some-text  > artifacts/test.txt
    - get-childitem artifacts
  artifacts:
    expire_in: 2 weeks
    paths:
    - artifacts

publish:
  stage: publish
  tags: ["runner:windows-docker", "windowsversion:1809"]
  dependencies: 
    - build
  script:
    - $result =  aws sts assume-role --role-arn "arn:aws:iam::486234852809:role/ci-datadog-windows-filter" --role-session-name AWSCLI-Session
    - $resultjson = $result | convertfrom-json
    - $credentials = $($resultjson.Credentials)
    - $Env:AWS_ACCESS_KEY_ID="$($credentials.AccessKeyId)"
    - $Env:AWS_SECRET_ACCESS_KEY="$($credentials.SecretAccessKey)"
    - $Env:AWS_SESSION_TOKEN="$($credentials.SessionToken)"
    - aws s3 cp artifacts/ s3://dd-windowsfilter/builds/tracer/${CI_COMMIT_SHA} --recursive --region us-east-1 --exclude "*" --include "*.zip" --include "*.msi"
