
stages:
  - build
  - publish
  
variables:
  DATADOG_AGENT_WINBUILDIMAGES: v5996510-a9e6a7d
    
build:
  stage: build
  tags: ["runner:windows-docker", "windowsversion:1809"]
  script:
    - if (Test-Path build-out) { remove-item -recurse -force build-out }
    - if (Test-Path artifacts) { remove-item -recurse -force artifacts }
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.ddbuild.io/DataDog/dd-continuous-profiler-dotnet.git
    - mkdir artifacts
    - touch artifacts/test.txt
    - get-childitem build-out
    - get-childitem artifacts
  artifacts:
    expire_in: 2 weeks
    paths:
    - artifacts

publish:
  stage: publish
  tags: ["runner:windows-docker", "windowsversion:1809"]
  dependencies: 
    - build
  script:
    - temp_credentials=$(aws sts assume-role --role-arn "arn:aws:iam::$727006795293:role/ci-datadog-windows-filter" --role-session-name AWSCLI-Session)
    - export AWS_ACCESS_KEY_ID=$(echo "$temp_credentials" | jq -r .Credentials.AccessKeyId)
    - export AWS_SECRET_ACCESS_KEY=$(echo "$temp_credentials" | jq -r .Credentials.SecretAccessKey)
    - export AWS_SESSION_TOKEN=$(echo "$temp_credentials" | jq -r .Credentials.SessionToken)
    - aws s3 cp artifacts/ s3://dd-windowsfilter/builds/tracer/${CI_COMMIT_SHA} --recursive --region us-east-1 --exclude "*" --include "*.zip" --include "*.msi"
